name: japhetobsioma
description: My personal website
publish_to: 'none' 
version: 3.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^1.0.0-dev.5
  url_launcher: ^6.0.9
  sizer: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true
