name: japhetobsioma
description: A new Flutter project.
publish_to: 'none' 
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^1.0.0-dev.5
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true
